
-- insert promotion
delete from LOGOS_JPA_PROMOTION;
insert into LOGOS_JPA_PROMOTION(PM_TYPE, PM_TITLE, PM_CONTENTS, PM_IMG_URL, PM_LINK_URL, PM_IS_ACTIVE) values ('Link', '2015 Summer Sale', '2015 summer sail is comming', '/resources/img/event/0001.jpg', 'http://www.naver.com', false);
insert into LOGOS_JPA_PROMOTION(PM_TYPE, PM_TITLE, PM_CONTENTS, PM_IMG_URL, PM_LINK_URL, PM_IS_ACTIVE) values ('Link', '2016 Summer Sale', '2015 summer sail is comming', '/resources/img/event/0001.jpg', 'http://www.daum.com', false);
insert into LOGOS_JPA_PROMOTION(PM_TYPE, PM_TITLE, PM_CONTENTS, PM_IMG_URL, PM_LINK_URL, PM_IS_ACTIVE) values ('Link', '2017 Summer Sale', '2015 summer sail is comming', '/resources/img/event/0001.jpg', 'http://www.naver.com', false);
insert into LOGOS_JPA_PROMOTION(PM_TYPE, PM_TITLE, PM_CONTENTS, PM_IMG_URL, PM_LINK_URL, PM_IS_ACTIVE) values ('Link', '2018 Summer Sale', '2018 winter sail is comming', '/resources/img/event/0002.jpg', 'http://www.naver.com', false);
insert into LOGOS_JPA_PROMOTION(PM_TYPE, PM_TITLE, PM_CONTENTS, PM_IMG_URL, PM_LINK_URL, PM_IS_ACTIVE) values ('Link', '2019 Summer Sale', '2019 summer sail is comming', '/resources/img/event/0003.jpg', 'http://www.naver.com', false);
insert into LOGOS_JPA_PROMOTION(PM_TYPE, PM_TITLE, PM_CONTENTS, PM_IMG_URL, PM_LINK_URL, PM_IS_ACTIVE) values ('Link', '2020 Summer Sale', '2020 summer sail is comming', '/resources/img/event/0004.jpg', 'http://www.naver.com', false);
insert into LOGOS_JPA_PROMOTION(PM_TYPE, PM_TITLE, PM_CONTENTS, PM_IMG_URL, PM_LINK_URL, PM_IS_ACTIVE) values ('Link', '2021 Summer Sale', '2021 summer sail is comming', '/resources/img/event/0005.jpg', 'http://www.naver.com', false);
insert into LOGOS_JPA_PROMOTION(PM_TYPE, PM_TITLE, PM_CONTENTS, PM_IMG_URL, PM_LINK_URL, PM_IS_ACTIVE) values ('Link', '2022 Summer Sale', '2022 summer sail is comming', '/resources/img/event/0006.jpg', 'http://www.naver.com', false);
insert into LOGOS_JPA_PROMOTION(PM_TYPE, PM_TITLE, PM_CONTENTS, PM_IMG_URL, PM_LINK_URL, PM_IS_ACTIVE) values ('Link', '2023 Summer Sale', '2023 summer sail is comming', '/resources/img/event/0007.jpg', 'http://www.naver.com', false);
insert into LOGOS_JPA_PROMOTION(PM_TYPE, PM_TITLE, PM_CONTENTS, PM_IMG_URL, PM_LINK_URL, PM_IS_ACTIVE) values ('Link', '2024 Summer Sale', '2024 summer sail is comming', '/resources/img/event/0008.jpg', 'http://www.naver.com', false);
insert into LOGOS_JPA_PROMOTION(PM_TYPE, PM_TITLE, PM_CONTENTS, PM_IMG_URL, PM_LINK_URL, PM_IS_ACTIVE) values ('Link', '2025 Summer Sale', '2025 summer sail is comming', '/resources/img/event/0009.jpg', 'http://www.naver.com', false);